# Generated by Django 5.0.6 on 2024-06-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceBillSundry',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bill_sundry_name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceHeader',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('invoice_number', models.IntegerField()),
                ('customer_name', models.CharField(max_length=255)),
                ('billing_address', models.CharField(max_length=255)),
                ('shipping_address', models.CharField(max_length=255)),
                ('gstin', models.CharField(max_length=255)),
                ('total_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
            ],
        ),
    ]
