# Generated by Django 5.0.6 on 2024-06-26 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceheader',
            name='bill_sundry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sample.invoicebillsundry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceheader',
            name='items',
            field=models.ManyToManyField(to='sample.invoiceitem'),
        ),
    ]
